language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: SFpZUL5b4u4cLnoSgKLkQ190POCS0U3e7j1JIXG6rOm6Irxj2zwVjn8XV5f4fs5iMNwuF7ZYpHIfMnnxmtij7ayeSCh0exxfdlytqasWyx0mOWsUDoK0nG4nyoSGFPi55qoNEvbmVvvgOZn580KuSFB/P5ILf2ckJz+/knmJ+jM=
  on:
    tags: true
    all_branches: true
